### ISSUE TITLE
Empty yolov5

### ISSUE THREAD

**Issue by wd-hub** [Stardust87/basketball-detection#1]
Hello Michal,
I would like to run this project but there is no scripts in the yolov5 dir. I tried to move the available net from "https://github.com/ultralytics/yolov5", however, it does not work due to many errors.
Do you use a customized yolov5?

**Comment by Crescentz** [comment]
the same question

**Comment by szacho** [comment]
Hi, sorry for the late response. There was modified YOLO (labels were processed differently). Since this repo gained some interest, I'm going to clean it up in few days

**Comment by Stardust87** [comment]
Hi, check new README.md for instructions how to add YOLOv5 code as a submodule to the project.
